// <auto-generated />
using MediaModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaModel.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20251129201629_MediaModelUser")]
    partial class MediaModelUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaModel.Audiobook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("author")
                        .IsFixedLength();

                    b.Property<int>("Bookid")
                        .HasColumnType("int")
                        .HasColumnName("bookid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("language")
                        .IsFixedLength();

                    b.Property<string>("Narrator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("narrator")
                        .IsFixedLength();

                    b.Property<string>("PublicationYear")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .HasColumnName("publicationYear")
                        .IsFixedLength();

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("publisher")
                        .IsFixedLength();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("title")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("Bookid");

                    b.ToTable("audiobooks", (string)null);
                });

            modelBuilder.Entity("MediaModel.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nchar(25)")
                        .HasColumnName("author")
                        .IsFixedLength();

                    b.Property<string>("CoAuthor")
                        .HasMaxLength(25)
                        .HasColumnType("nchar(25)")
                        .HasColumnName("coAuthor")
                        .IsFixedLength();

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("language")
                        .IsFixedLength();

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int")
                        .HasColumnName("publicationYear");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("publisher")
                        .IsFixedLength();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("title")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("books");
                });

            modelBuilder.Entity("MediaModel.Audiobook", b =>
                {
                    b.HasOne("MediaModel.Book", "Book")
                        .WithMany()
                        .HasForeignKey("Bookid")
                        .IsRequired()
                        .HasConstraintName("FK_audiobooks_books");

                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
